//! Compiles the operator UI (`ui/dist`) and the built-in hordes into the server binary, so a
//! single `kowalski` serves everything. Both are optional: a build without them (a crates.io
//! build, or a checkout where the UI was not built) still works and says what is missing.
//!
//! - UI: `$KOWALSKI_UI_DIST`, else `../ui/dist` (run `cd ui && bun run build` first).
//! - Built-in hordes: the directories named in `BUILTIN_HORDES` under `../examples`.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Hordes shipped inside the binary, by directory name under `examples/`.
const BUILTIN_HORDES: &[&str] = &["spreadsheet-analyst", "morning-brief", "folder-watcher", "url-summarizer", "knowledge-compiler"];

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    let mut entries: Vec<_> = rd.flatten().collect();
    entries.sort_by_key(|e| e.path());
    for e in entries {
        let p = e.path();
        let name = e.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') {
            continue;
        }
        if p.is_dir() {
            // a horde's workdir holds run output, never definitions
            if name == "output" && dir != root {
                continue;
            }
            if name == "output" && root.join("horde.md").exists() {
                continue;
            }
            collect(root, &p, out);
        } else if p.is_file() {
            let rel = p.strip_prefix(root).unwrap().to_string_lossy().replace('\\', "/");
            out.push((rel, p));
        }
    }
}

fn table(name: &str, files: &[(String, PathBuf)]) -> String {
    let mut s = format!("pub static {name}: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in files {
        let _ = writeln!(s, "    ({rel:?}, include_bytes!({:?})),", abs.display().to_string());
    }
    s.push_str("];\n");
    s
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace = manifest.parent().unwrap_or(&manifest).to_path_buf();

    println!("cargo:rerun-if-env-changed=KOWALSKI_UI_DIST");
    let ui_dir = std::env::var("KOWALSKI_UI_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|_| workspace.join("ui").join("dist"));
    println!("cargo:rerun-if-changed={}", ui_dir.display());
    let mut ui = Vec::new();
    if ui_dir.join("index.html").is_file() {
        collect(&ui_dir, &ui_dir, &mut ui);
    } else {
        println!(
            "cargo:warning=operator UI not embedded: {} has no index.html (cd ui && bun run build)",
            ui_dir.display()
        );
    }

    let mut hordes = Vec::new();
    for id in BUILTIN_HORDES {
        let dir = workspace.join("examples").join(id);
        println!("cargo:rerun-if-changed={}", dir.display());
        let mut files = Vec::new();
        collect(&dir, &dir, &mut files);
        hordes.extend(files.into_iter().map(|(rel, abs)| (format!("{id}/{rel}"), abs)));
    }

    let mut code = String::from("// generated by build.rs\n");
    code.push_str(&table("UI_FILES", &ui));
    code.push_str(&table("BUILTIN_HORDE_FILES", &hordes));
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_assets.rs");
    std::fs::write(out, code).unwrap();
}
