#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAW_DIR="${ROOT_DIR}/raw/sources"
SUM_DIR="${ROOT_DIR}/wiki/summaries"
CONCEPT_DIR="${ROOT_DIR}/wiki/concepts"
INDEX_FILE="${ROOT_DIR}/wiki/index.md"

mkdir -p "${SUM_DIR}" "${CONCEPT_DIR}"

latest_source="$(ls -1 "${RAW_DIR}"/*.md 2>/dev/null | sort | tail -n 1 || true)"
if [[ -z "${latest_source}" ]]; then
  echo "No source files found under ${RAW_DIR}"
  exit 1
fi

base_name="$(basename "${latest_source}" .md)"
summary_file="${SUM_DIR}/${base_name}.md"

cat > "${summary_file}" <<EOF
# Source Summary: ${base_name}

## Source File
- ${latest_source}

## Summary
Placeholder summary generated by scaffold script.
Replace this with a Kowalski compiler agent output.

## Extracted Concepts
- [[Knowledge Compiler]]
EOF

concept_file="${CONCEPT_DIR}/knowledge-compiler.md"
if [[ ! -f "${concept_file}" ]]; then
  cat > "${concept_file}" <<'EOF'
# Knowledge Compiler

## Summary
An agent-driven workflow that compiles raw sources into a structured markdown knowledge graph.

## Related Concepts
- [[Local-first AI]]
- [[Linked Markdown]]
EOF
fi

{
  echo "# Knowledge Compiler Index"
  echo
  echo "## Concepts"
  concept_found=0
  for f in "${CONCEPT_DIR}"/*.md; do
    [[ -e "${f}" ]] || continue
    concept_found=1
    echo "- [[${f##*/}]]" | sed 's/\.md]]$/]]/'
  done
  if [[ "${concept_found}" -eq 0 ]]; then
    echo "- (none yet)"
  fi
  echo
  echo "## Source Summaries"
  summary_found=0
  for f in "${SUM_DIR}"/*.md; do
    [[ -e "${f}" ]] || continue
    summary_found=1
    echo "- [[${f##*/}]]" | sed 's/\.md]]$/]]/'
  done
  if [[ "${summary_found}" -eq 0 ]]; then
    echo "- (none yet)"
  fi
} > "${INDEX_FILE}"

echo "Compiled latest source into wiki artifacts."
